# Payor (HLS) current-state vendor console specs — Unity Health Plan x Marcus Chen, Silver HMO
SC = "hls-payor"
SPECS = [
{
  "slug": f"component-benefitfocus-enrollment-{SC}.html",
  "title": "Benefitfocus eEnrollment", "desc": "Stylized mock evoking a benefits enrollment platform in a health-plan onboarding workflow. Not a literal screenshot.",
  "logo": "eEnrollment · Benefitfocus (evocative)", "user": "Okafor, R. — Enrollment Ops",
  "headbg": "#15384A", "accent": "#7AB648", "bg": "#F2F5F4",
  "tabs": [("Members", False), ("Enrollment", True), ("Plans", False), ("Files", False), ("Reports", False)],
  "crumb": "<b>Enrollment</b> &nbsp;&gt;&nbsp; Group 88421 · Unity Silver HMO &nbsp;&gt;&nbsp; Chen, Marcus",
  "crumbChip": "Pending — dependent SSN", "crumbChipClass": "warn",
  "nav": [
    {"label":"Member Search","svg":'<circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/>'},
    {"label":"Enrollment · Chen, M.","on":True,"svg":'<rect x="3" y="6" width="18" height="14" rx="2"/><path d="M9 6V4h6v2"/>'},
    {"label":"Dependents","badge":"2","svg":'<circle cx="9" cy="8" r="3"/><path d="M3 20c0-3 3-5 6-5"/><circle cx="17" cy="10" r="2"/>'},
    {"label":"Documents","alert":"3","svg":'<path d="M14 3H6v18h12V7z"/><path d="M14 3v4h4"/>'},
    {"head":"Open Groups"},
    {"label":"Unity Silver HMO 2026"},
    {"label":"Unity Bronze PPO 2026"},
  ],
  "mainTitle": "Enrollment — Chen, Marcus A.",
  "kv": [("Member ID","UNY-884213 (provisional)"),("Plan","Unity Silver HMO · 2026"),("Effective","01-01-2026 — not yet active"),("Source","Broker spreadsheet upload · batch B-4471"),("Status",'<span class="chip warn">Held — 2 dependent SSNs missing</span>')],
  "table": {"cols":["Step","Owner","State","System"],"rows":[
    ["Application received","Broker","<span class='chip ok'>Complete</span>","CSV upload"],
    ["Demographics keyed","Ops","<span class='chip ok'>Complete</span>","eEnrollment"],
    ["Dependent verification","Ops","<span class='chip warn'>Blocked — SSN x2</span>","Email"],
    ["Eligibility load","Auto","<span class='chip stale'>Not started</span>","HealthRules EDI"],
    ["ID card request","Auto","<span class='chip stale'>Not started</span>","Fulfillment"],
  ]},
  "aside": {"h5":"Pending Items","tasks":[("Email broker: dependent SSNs","Sent 12/18"),("Re-key after reply","Manual"),("Hold eligibility load","Until docs")],"noteHead":"Hand-off","note":"Clean records get re-keyed into <b>HealthRules Payor</b> by hand. Nothing is active until the EDI batch runs."},
  "friction": "Broker submits enrollments as a spreadsheet. Dependent SSNs arrive by email and are re-keyed into the core admin system.",
  "config": {"vendor":"Benefitfocus eEnrollment (evocative)","scope":"HLS · Payor","state":"Current","useCase":"Member enrollment","archetype":"console"},
},
{
  "slug": f"component-healthedge-core-admin-{SC}.html",
  "title": "HealthRules Payor — HealthEdge", "desc": "Stylized mock evoking a core health-plan administration system (eligibility / EDI). Not a literal screenshot.",
  "logo": "HealthRules Payor · HealthEdge (evocative)", "user": "Batch Service · EDI",
  "headbg": "#0B2E3B", "accent": "#00A7B5", "bg": "#F1F5F6",
  "tabs": [("Member", True), ("Eligibility", False), ("Benefits", False), ("Claims", False), ("EDI", False)],
  "crumb": "<b>Member</b> &nbsp;&gt;&nbsp; UNY-884213 &nbsp;&gt;&nbsp; Eligibility",
  "crumbChip": "270/271 pending", "crumbChipClass": "stale",
  "nav": [
    {"label":"Member · UNY-884213","on":True,"svg":'<circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 4-6 8-6s8 2 8 6"/>'},
    {"label":"Eligibility","svg":'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="m8 12 3 3 5-6"/>'},
    {"label":"Benefit Plan","svg":'<path d="M14 3H6v18h12V7z"/><path d="M14 3v4h4"/>'},
    {"label":"Accumulators","svg":'<path d="m3 17 6-6 4 4 8-8"/>'},
    {"head":"Interfaces"},
    {"label":"270/271 EDI · nightly"},
    {"label":"834 Enrollment · nightly"},
  ],
  "mainTitle": "Eligibility — Chen, Marcus A.",
  "kv": [("Member ID","UNY-884213"),("Plan","Silver HMO · HIOS 12345AZ"),("Eligibility","Inactive — awaiting 270/271"),("Last EDI run","Tonight 02:00 MST"),("PCP","Unassigned")],
  "table": {"cols":["Check","Result","Source","Latency"],"rows":[
    ["Demographic match","<span class='chip ok'>Match</span>","834 batch","18h"],
    ["Coverage active","<span class='chip warn'>No — pending</span>","270/271","24–48h"],
    ["Other coverage (COB)","<span class='chip stale'>Unknown</span>","Manual","—"],
    ["PCP assignment","<span class='chip warn'>Open</span>","Provider file","—"],
  ]},
  "aside": {"h5":"Batch Status","tasks":[("834 enrollment load","Queued 02:00"),("270/271 eligibility","After 834"),("Member portal sync","After eligibility")],"noteHead":"Latency","note":"The member can't be verified at point of care until the <b>nightly EDI batch</b> clears. 24–48h before active."},
  "friction": "Eligibility is confirmed by a nightly 270/271 EDI batch. 24–48h pass before the member shows active anywhere.",
  "config": {"vendor":"HealthEdge HealthRules Payor (evocative)","scope":"HLS · Payor","state":"Current","useCase":"Eligibility / EDI","archetype":"console"},
},
{
  "slug": f"component-quadient-eoc-hipaa-{SC}.html",
  "title": "Quadient Inspire — Member Comms", "desc": "Stylized mock evoking a customer-communications / document-output platform mailing plan documents. Not a literal screenshot.",
  "logo": "Inspire · Member Communications (evocative)", "user": "Comms Batch · Print",
  "headbg": "#2A2350", "accent": "#9B7BE0", "bg": "#F4F2F8",
  "tabs": [("Templates", False), ("Jobs", True), ("Proofs", False), ("Archive", False)],
  "crumb": "<b>Jobs</b> &nbsp;&gt;&nbsp; J-2026-11842 · Welcome Packet &nbsp;&gt;&nbsp; Chen, Marcus",
  "crumbChip": "Print queue", "crumbChipClass": "stale",
  "nav": [
    {"label":"Print Jobs","on":True,"svg":'<rect x="6" y="9" width="12" height="7" rx="1"/><path d="M6 9V4h12v5"/><path d="M8 16h8v4H8z"/>'},
    {"label":"Welcome Packet","svg":'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>'},
    {"label":"HIPAA Authorization","alert":"wet-ink","svg":'<path d="M14 3H6v18h12V7z"/><path d="M14 3v4h4"/>'},
    {"head":"Documents"},
    {"label":"Summary of Benefits (SBC)"},
    {"label":"Evidence of Coverage (EOC)"},
  ],
  "mainTitle": "Welcome Packet — Chen, Marcus A.",
  "kv": [("Job","J-2026-11842"),("Channel","Print → USPS First Class"),("Includes","SBC · EOC · HIPAA auth form"),("Generated","PDF · 38 pages"),("Return path",'<span class="chip warn">Wet-ink HIPAA by fax</span>')],
  "table": {"cols":["Document","Action needed","Channel","Turnaround"],"rows":[
    ["Summary of Benefits","Read","Mail","5–7 days"],
    ["Evidence of Coverage","Read","Mail","5–7 days"],
    ["HIPAA authorization","Sign + return","Mail → Fax","10–14 days"],
    ["PCP selection form","Complete + return","Mail → Fax","10–14 days"],
  ]},
  "aside": {"h5":"Return Handling","tasks":[("Fax inbound → imaging","Manual"),("Index to member record","Days later"),("Exceptions to Ops queue","If illegible")],"noteHead":"Risk","note":"Signed HIPAA forms come back by <b>fax</b>, get scanned, and are indexed to the member record days later — or lost."},
  "friction": "Plan documents are mailed as a PDF packet. The HIPAA authorization returns by wet-ink fax and is scanned to imaging days later.",
  "config": {"vendor":"Quadient Inspire (evocative)","scope":"HLS · Payor","state":"Current","useCase":"Plan documents / consent","archetype":"console"},
},
{
  "slug": f"component-fulfillment-id-card-{SC}.html",
  "title": "ID Card & Kit Fulfillment", "desc": "Stylized mock evoking a third-party ID-card and welcome-kit fulfillment vendor. Not a literal screenshot.",
  "logo": "Fulfillment Services · ID Cards (evocative)", "user": "Vendor Portal · Unity",
  "headbg": "#3A2E14", "accent": "#E0A92E", "bg": "#F6F4EE",
  "tabs": [("Orders", True), ("Inventory", False), ("Shipping", False), ("SLA", False)],
  "crumb": "<b>Orders</b> &nbsp;&gt;&nbsp; ORD-44218 · ID Card + Welcome Kit &nbsp;&gt;&nbsp; Chen, M.",
  "crumbChip": "7–10 business days", "crumbChipClass": "stale",
  "nav": [
    {"label":"Order · ORD-44218","on":True,"svg":'<rect x="3" y="6" width="18" height="14" rx="2"/><path d="M3 10h18"/>'},
    {"label":"Card Stock","svg":'<rect x="3" y="6" width="18" height="12" rx="2"/><path d="M3 10h18"/>'},
    {"label":"Shipping","svg":'<rect x="1" y="7" width="14" height="9"/><path d="M15 10h4l3 3v3h-7"/>'},
    {"head":"Queue"},
    {"label":"Daily print run · 18:00"},
  ],
  "mainTitle": "Order — ID Card + Welcome Kit",
  "kv": [("Order","ORD-44218"),("Member","Chen, Marcus A. · UNY-884213"),("Trigger","Eligibility active (pending)"),("Print run","Next 18:00 batch"),("Est. delivery",'<span class="chip stale">7–10 business days</span>')],
  "table": {"cols":["Stage","State","Owner"],"rows":[
    ["Order received","<span class='chip warn'>Held — eligibility pending</span>","Auto"],
    ["Card personalization","<span class='chip stale'>Queued</span>","Vendor"],
    ["Kit assembly","<span class='chip stale'>Queued</span>","Vendor"],
    ["Mail / track","<span class='chip stale'>Not started</span>","USPS"],
  ]},
  "aside": {"h5":"Member Impact","tasks":[("No digital card","Until mail"),("Can't fill Rx","No card #"),("Calls service center","Day 3+")],"noteHead":"Gap","note":"The member <b>can't transact</b> — pharmacy, PCP visit — until the physical card arrives a week-plus later."},
  "friction": "ID cards are printed and mailed by a third-party vendor — 7–10 business days. The member can't transact until the card arrives.",
  "config": {"vendor":"ID Card Fulfillment vendor (evocative)","scope":"HLS · Payor","state":"Current","useCase":"ID card issuance","archetype":"console"},
},
{
  "slug": f"component-um-prior-auth-fax-{SC}.html",
  "title": "Utilization Management — MCG", "desc": "Stylized mock evoking a utilization-management / prior-authorization platform with fax intake. Not a literal screenshot.",
  "logo": "Utilization Mgmt · MCG (evocative)", "user": "Nurse, T. — UM Review",
  "headbg": "#13314A", "accent": "#3F8FD0", "bg": "#F1F4F7",
  "tabs": [("Queue", True), ("Cases", False), ("Criteria", False), ("Letters", False)],
  "crumb": "<b>Queue</b> &nbsp;&gt;&nbsp; PA-2026-90713 · MRI Lumbar &nbsp;&gt;&nbsp; Chen, M.",
  "crumbChip": "Fax intake", "crumbChipClass": "warn",
  "nav": [
    {"label":"UM Queue","on":True,"svg":'<path d="M3 6h18M3 12h18M3 18h12"/>'},
    {"label":"PA-2026-90713","svg":'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="m8 12 3 3 5-6"/>'},
    {"label":"Clinical Criteria","svg":'<path d="M14 3H6v18h12V7z"/>'},
    {"head":"Intake"},
    {"label":"Fax inbound","alert":"22"},
    {"label":"Provider portal"},
  ],
  "mainTitle": "Prior Authorization — MRI Lumbar Spine",
  "kv": [("Request","PA-2026-90713"),("Member","Chen, Marcus A. · UNY-884213"),("Provider","Desert Ortho · NPI 1487…"),("Received","Fax · 14 pages"),("Status",'<span class="chip warn">Re-keying from fax</span>')],
  "table": {"cols":["Step","Owner","State","Visible to provider?"],"rows":[
    ["Fax received","Intake","<span class='chip ok'>Logged</span>","No"],
    ["Re-key to case","UM nurse","<span class='chip warn'>In progress</span>","No"],
    ["Criteria check (MCG)","UM nurse","<span class='chip stale'>Pending</span>","No"],
    ["Decision letter","Auto","<span class='chip stale'>Not started</span>","Mail, days later"],
  ]},
  "aside": {"h5":"Turnaround","tasks":[("Fax → case re-key","Same day"),("Clinical review","1–3 days"),("Letter by mail","+3 days")],"noteHead":"Blind spot","note":"Status is <b>invisible to the member and provider</b> for days. They call to ask where it stands."},
  "friction": "Providers fax the prior-auth request. A UM nurse re-keys it. Status stays invisible to member and provider for days.",
  "config": {"vendor":"Utilization Management / MCG (evocative)","scope":"HLS · Payor","state":"Current","useCase":"Prior authorization","archetype":"console"},
},
{
  "slug": f"component-qnxt-claims-member-{SC}.html",
  "title": "TriZetto QNXT — Claims", "desc": "Stylized mock evoking a claims-administration platform and scattered member service records. Not a literal screenshot.",
  "logo": "QNXT · Claims Administration (evocative)", "user": "Service Center · Member",
  "headbg": "#1C2B4A", "accent": "#5A7FD6", "bg": "#F2F4F8",
  "tabs": [("Member", True), ("Claims", False), ("EOB", False), ("Notes", False)],
  "crumb": "<b>Member</b> &nbsp;&gt;&nbsp; UNY-884213 &nbsp;&gt;&nbsp; Claim CLM-771204",
  "crumbChip": "EOB inquiry", "crumbChipClass": "warn",
  "nav": [
    {"label":"Member · UNY-884213","on":True,"svg":'<circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 4-6 8-6s8 2 8 6"/>'},
    {"label":"Claims History","svg":'<path d="M14 3H6v18h12V7z"/><path d="M14 3v4h4"/>'},
    {"label":"EOB / Remit","svg":'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M7 9h10M7 13h6"/>'},
    {"label":"Call Notes","alert":"4","svg":'<path d="M22 16.9v3a2 2 0 0 1-2.2 2A19 19 0 0 1 3 5.2 2 2 0 0 1 5 3h3a2 2 0 0 1 2 1.7l.6 2.6a2 2 0 0 1-.5 2L8.6 10a16 16 0 0 0 6 6l.7-1.5a2 2 0 0 1 2-.5l2.6.6A2 2 0 0 1 22 16.9Z"/>'},
    {"head":"Records live in"},
    {"label":"QNXT · Imaging · Call logs"},
  ],
  "mainTitle": "Member Record — Chen, Marcus A.",
  "kv": [("Member ID","UNY-884213"),("First claim","CLM-771204 · Desert Ortho"),("EOB","Mailed 12/29 · paper"),("Inquiry","'Why was $214 not covered?'"),("Record location",'<span class="chip warn">QNXT + imaging + call logs</span>')],
  "table": {"cols":["Artifact","System","Reachable in call?"],"rows":[
    ["Claim line detail","QNXT","<span class='chip warn'>Tab-hunt</span>"],
    ["EOB PDF","Imaging","<span class='chip warn'>Separate lookup</span>"],
    ["Prior-auth tie-in","UM platform","<span class='chip stale'>Not linked</span>"],
    ["Prior call notes","Call logs","<span class='chip warn'>Free text</span>"],
  ]},
  "aside": {"h5":"This Call","tasks":[("Pull claim in QNXT","2 min"),("Find EOB in imaging","3 min"),("Read prior notes","2 min")],"noteHead":"Fragmentation","note":"No single member record. The rep stitches <b>QNXT, imaging, and call logs</b> live while the member waits."},
  "friction": "The first claim adjudicates in QNXT. The member calls to understand the EOB — records are scattered across QNXT, imaging, and call logs.",
  "config": {"vendor":"TriZetto QNXT (evocative)","scope":"HLS · Payor","state":"Current","useCase":"Claims / member service","archetype":"console"},
},
]
